from typing import Dict, Any


class ReportAgent:
    """
    Report Agent

    Combines the outputs of the Image Analysis,
    Risk & Uncertainty, and Explanation agents into
    one structured dermatology analysis report.

    This report is AI-assisted and is not a definitive
    medical diagnosis.
    """

    name = "Report Agent"

    def generate_report(
        self,
        image_analysis: Dict[str, Any],
        risk_analysis: Dict[str, Any],
        explanation: Dict[str, Any],
    ) -> Dict[str, Any]:

        # ---------------------------------------------
        # 1. Extract core information
        # ---------------------------------------------

        prediction = image_analysis.get(
            "prediction"
        )

        confidence = image_analysis.get(
            "confidence", 0
        )

        probabilities = image_analysis.get(
            "probabilities",
            {}
        )

        similarity = image_analysis.get(
            "similarity", 0
        )

        entropy = image_analysis.get(
            "entropy", 0
        )

        ood = image_analysis.get(
            "ood", True
        )

        gradcam_available = image_analysis.get(
            "gradcam_available",
            False,
        )

        gradcam_url = image_analysis.get(
            "gradcam_url"
        )

        assessment = risk_analysis.get(
            "assessment",
            "Unknown",
        )

        review_required = risk_analysis.get(
            "review_required",
            True,
        )

        # ---------------------------------------------
        # 2. Build report status
        # ---------------------------------------------

        if ood:

            report_status = "Unsupported Image"

        elif review_required:

            report_status = "Review Recommended"

        else:

            report_status = "Analysis Completed"

        # ---------------------------------------------
        # 3. Build report
        # ---------------------------------------------

        report = {
            "title": "Dermatology AI Analysis Report",

            "status": report_status,

            "prediction": {
                "class": prediction,
                "condition": explanation.get(
                    "condition_name",
                    prediction,
                ),
                "confidence": confidence,
                "probabilities": probabilities,
            },

            "image_assessment": {
                "ood": ood,
                "assessment": assessment,
                "review_required": review_required,
                "feature_similarity": similarity,
                "prediction_entropy": entropy,
            },

            "explanation": {
                "summary": explanation.get(
                    "summary"
                ),
                "interpretation": explanation.get(
                    "interpretation"
                ),
                "next_step": explanation.get(
                    "next_step"
                ),
            },

            "explainability": {
                "gradcam_available":
                    gradcam_available,

                "gradcam_url":
                    gradcam_url,

                "note": explanation.get(
                    "explanation_note"
                ),
            },

            "disclaimer": (
                "This report is generated by an "
                "AI-assisted research prototype. "
                "It is not a definitive medical diagnosis "
                "and should not replace evaluation by a "
                "qualified healthcare professional."
            ),

            "agent": self.name,

            "status": "completed",
        }

        return report


# --------------------------------------------------
# Shared agent instance
# --------------------------------------------------

report_agent = ReportAgent()